---
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: art-stage-mirror-set
  namespace: openshift-marketplace
spec:
  imageDigestMirrors:
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/frr-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ingress-node-firewall-operator-bundle
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ingress-node-firewall-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ingress-node-firewall-rhel9-operator
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/kubernetes-nmstate-operator-bundle
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/kubernetes-nmstate-rhel9-operator
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/metallb-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/metallb-rhel9-operator
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/nmstate-console-plugin-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-aws-efs-csi-driver-container-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-aws-efs-csi-driver-operator-bundle
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-aws-efs-csi-driver-rhel9-operator
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-cloud-event-proxy-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-clusterresourceoverride-operator-bundle
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-clusterresourceoverride-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-clusterresourceoverride-rhel9-operator
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-csi-external-provisioner-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-csi-external-resizer-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-csi-external-snapshotter-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-csi-livenessprobe-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-csi-node-driver-registrar-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-dpu-daemon-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-dpu-operator-bundle
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-dpu-rhel9-operator
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-gcp-filestore-csi-driver-operator-bundle
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-gcp-filestore-csi-driver-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-gcp-filestore-csi-driver-rhel9-operator
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-kube-rbac-proxy-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-kubernetes-nmstate-handler-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-local-storage-diskmaker-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-local-storage-mustgather-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-local-storage-operator-bundle
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-local-storage-rhel9-operator
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-metallb-operator-bundle
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-ptp-operator-bundle
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-ptp-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-ptp-rhel9-operator
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-secrets-store-csi-driver-operator-bundle
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-secrets-store-csi-driver-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-secrets-store-csi-driver-rhel9-operator
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-smb-csi-driver-operator-bundle
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-smb-csi-driver-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-smb-csi-driver-rhel9-operator
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-sriov-dp-admission-controller-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-sriov-infiniband-cni-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-sriov-network-config-daemon-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-sriov-network-device-plugin-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-sriov-network-metrics-exporter-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-sriov-network-operator-bundle
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-sriov-network-rhel9-operator
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-sriov-network-webhook-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-vertical-pod-autoscaler-operator-bundle
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-vertical-pod-autoscaler-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/ose-vertical-pod-autoscaler-rhel9-operator
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/openshift4/sriov-cni-rhel9
