---
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: art-images-mirror-set
  namespace: openshift-marketplace
spec:
  imageDigestMirrors:
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/cert-manager/cert-manager-istio-csr-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/cert-manager/cert-manager-operator-bundle
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/cert-manager/cert-manager-operator-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/cert-manager/cert-manager-trust-manager-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/cert-manager/jetstack-cert-manager-acmesolver-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/cert-manager/jetstack-cert-manager-rhel9
