---
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: art-images-mirror-set
  namespace: openshift-marketplace
spec:
  imageDigestMirrors:
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/addon-manager-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/azure-service-operator-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/backplane-must-gather-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/backplane-rhel9-operator
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/capoa-bootstrap-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/capoa-control-plane-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/cloudevents-conductor-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/cluster-api-provider-agent-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/cluster-api-provider-aws-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/cluster-api-provider-azure-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/cluster-api-provider-kubevirt-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/cluster-curator-controller-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/cluster-image-set-controller-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/cluster-permission-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/cluster-proxy-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/clusterclaims-controller-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/clusterlifecycle-state-metrics-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/console-mce-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/discovery-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/hive-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/hypershift-addon-rhel9-operator
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/hypershift-cli-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/hypershift-rhel9-operator
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/image-based-install-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/kube-rbac-proxy-mce-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/maestro-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/managed-serviceaccount-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/managedcluster-import-controller-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/mce-capi-webhook-config-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/mce-operator-bundle
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/multicloud-manager-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/placement-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/provider-credential-controller-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/registration-operator-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/registration-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images
    source: registry.redhat.io/multicluster-engine/work-rhel9
